@startuml
left to right direction
skinparam BackgroundColor transparent
skinparam componentStyle rectangle



package "bin" {
  [luadocer]
  [lua-plantuml]
  [lua-highlighter]
  [lua-formatter]
  [lua-addComments]
  [lfs.so]
}

package "lib" {
    [alt_getopt.lua]
    [cosmo.lua]
    [leg.lua]
    [logging.lua]
    [ltn12.lua]
    [markdown.lua]
    [mime.lua]
    [re.lua]
    [socket.lua]
    [strict.lua]
    [lpeg.so]

    component comments {
        [comments.aliases.lua] 
        [comments.common.lua]
        [comments.custom.lua]
        [comments.explua.lua]
        [comments.init.lua]
        [comments.ldoc.lua]
        [comments.leg.lua]
        [comments.literate.lua]
        [comments.luadoc.lua]
        [comments.templateComments.lua]
    }

    component cosmo {
        [cosmo.fill.lua]
        [cosmo.grammar.lua]
    }

    component leg {
        [leg.grammar.lua]
        [leg.parser.lua]
        [leg.scanner.lua]
    }
    component literate {
        [literate.init.lua]
        [literate.util.lua]
    }
    component logging {
        [logging.console.lua]
        [logging.email.lua]
        [logging.file.lua]
        [logging.rolling_file.lua]
        [logging.socket.lua]
        [logging.sql.lua]
    }
    component _luadocer {
        [_luadocer.config.lua]
        component _luadocer.doclet {
            [_luadocer.doclet.debug.lua]
            [_luadocer.doclet.formatter.lua]
            component html{
                
            }
            [_luadocer.doclet.html.lua]
            [_luadocer.doclet.raw.lua]
            [_luadocer.doclet.templates.lua]
        }
        [_luadocer.init.lua]
        [_luadocer.io.lua]
        [_luadocer.lp.lua]
        component _luadocer.taglet {
            [_luadocer.taglet.standard.lua]
            component _luadocer.taglet.standard {
                [_luadocer.taglet.standard.aliases.lua]
                [_luadocer.taglet.standard.tags.lua]
            }

        }
        [_luadocer.util.lua]
    }

    component luaplantuml {
        [luaplantuml.generate_uml.lua]
        [luaplantuml.init.lua]
    }
    component luapretty {
        [luapretty.ast_helper.lua]
        [luapretty.formatter.lua]
        [luapretty.highlighter.lua]
        component luapretty.templates{
            [luapretty.templates.default.lua]
        }
    }    
    component metrics {

        component metrics.captures {
            [metrics.captures.AST.lua]
            [metrics.captures.block.lua]
            [metrics.captures.cyclomatic.lua]
            [metrics.captures.document_metrics.lua]
            [metrics.captures.functiontree.lua]
            [metrics.captures.halstead.lua]
            [metrics.captures.infoflow.lua]
            [metrics.captures.LOC.lua]
            [metrics.captures.smells.lua]
            [metrics.captures.statements.lua]
        }
        [metrics.init.lua]
        [metrics.lookup.lua]
        component metrics.luadoc {
            [metrics.luadoc.captures.lua]
            [metrics.luadoc.commentParser.lua]
        }
        [metrics.rules.lua]
        component metrics.templates {
            [metrics.templates.docMetricsTemplates.lua]
            [metrics.templates.funcTableTemplates.lua]
            [metrics.templates.init.lua]
            [metrics.templates.smellTemplates.lua]
            [metrics.templates.utils.lua]
        }
        [metrics.utils.lua]
    }
    component mime {
        [mime.core.so]
    }
    component socket {
        [socket.core.so]
    }
}

'luadocer
[luadocer]----->[_luadocer.init.lua]
[luadocer]----->[_luadocer.util.lua]

'lua-addComments
[lua-addComments]----->[comments.templateComments.lua]

'lua-formatter
[lua-formatter]----->[luapretty.formatter.lua]
[lua-formatter]----->[alt_getopt.lua]

'lua-highlighter
[lua-highlighter]----->[luapretty.highlighter.lua]
[lua-highlighter]----->[alt_getopt.lua]
[lua-highlighter]----->[_luadocer.doclet.debug.lua]

'lua-plantuml
[lua-plantuml]----->[luaplantuml.init.lua]
[lua-plantuml]----->[alt_getopt.lua]
[lua-plantuml]----->[lfs.so]


'cosmo
[cosmo.lua]----->[cosmo.grammar.lua]
[cosmo.lua]----->[cosmo.fill.lua]

'leg
[leg.lua]----->[leg.grammar.lua]
[leg.lua]----->[leg.scanner.lua]
[leg.lua]----->[leg.parser.lua]

'mime
[mime.lua]----->[ltn12.lua]
[mime.lua]----->[mime.core.so]

're
[re.lua]----->[lpeg.so]

'socket
[socket.lua]----->[socket.core.so]

'comments
[comments.common.lua]----->[comments.aliases.lua]
[comments.custom.lua]----->[re.lua]
[comments.explua.lua]----->[re.lua]
[comments.explua.lua]----->[comments.common.lua]
[comments.init.lua]----->[re.lua]

[comments.init.lua]----->[comments.explua.lua]
[comments.init.lua]----->[comments.luadoc.lua]
[comments.init.lua]----->[comments.literate.lua]
[comments.init.lua]----->[comments.custom.lua]
[comments.init.lua]----->[comments.ldoc.lua]
[comments.init.lua]----->[comments.leg.lua]

[comments.ldoc.lua]----->[re.lua]
[comments.ldoc.lua]----->[comments.common.lua]
[comments.leg.lua]----->[comments.common.lua]
[comments.literate.lua]----->[re.lua]
[comments.luadoc.lua]----->[comments.common.lua]
[comments.luadoc.lua]----->[re.lua]

[comments.templateComments.lua]----->[metrics.init.lua]
[comments.templateComments.lua]----->[metrics.utils.lua]
[comments.templateComments.lua]----->[metrics.utils.lua]
'je tu este nepouzivana zavislot na getdoc.utils
[comments.templateComments.lua]----->[lfs.so]

'cosmo
[cosmo.fill.lua]----->[cosmo.grammar.lua]
[cosmo.grammar.lua]----->[re.lua]
[cosmo.grammar.lua]----->[lpeg.so]

'leg
[leg.grammar.lua]----->[lpeg.so]
[leg.parser.lua]----->[lpeg.so]
[leg.parser.lua]----->[leg.grammar.lua]
[leg.parser.lua]----->[leg.scanner.lua]
[leg.scanner.lua]----->[lpeg.so]

'literate
[literate.init.lua]----->[luapretty.highlighter.lua]
[literate.init.lua]----->[luapretty.ast_helper.lua]
[literate.init.lua]----->[literate.util.lua]
[literate.init.lua]----->[_luadocer.doclet.html.lua]
[literate.init.lua]----->[markdown.lua]


'_luadocer
[_luadocer.init.lua]----->[_luadocer.util.lua]
[_luadocer.init.lua]----->[_luadocer.config.lua]
[_luadocer.util.lua]----->[re.lua]
[_luadocer.util.lua]----->[lfs.so]
    'doclet
    [_luadocer.doclet.formatter.lua]----->[_luadocer.util.lua]
    [_luadocer.doclet.html.lua]----->[lfs.so]
    [_luadocer.doclet.html.lua]----->[_luadocer.util.lua]
    [_luadocer.doclet.html.lua]----->[_luadocer.init.lua]
    [_luadocer.doclet.html.lua]----->[_luadocer.io.lua]
    [_luadocer.doclet.html.lua]----->[luapretty.highlighter.lua]
    [_luadocer.doclet.html.lua]----->[luapretty.formatter.lua]
    [_luadocer.doclet.html.lua]----->[luapretty.ast_helper.lua]
    [_luadocer.doclet.html.lua]----->[metrics.init.lua]
    [_luadocer.doclet.html.lua]----->[luaplantuml.init.lua]
    [_luadocer.doclet.html.lua]----->[metrics.templates.docMetricsTemplates.lua]
    [_luadocer.doclet.html.lua]----->[metrics.templates.funcTableTemplates.lua]
    [_luadocer.doclet.html.lua]----->[metrics.templates.init.lua]
    [_luadocer.doclet.html.lua]----->[metrics.templates.smellTemplates.lua]
    [_luadocer.doclet.html.lua]----->[_luadocer.doclet.templates.lua]

    'taglet   
    [_luadocer.taglet.standard.lua]----->[_luadocer.io.lua]
    [_luadocer.taglet.standard.lua]----->[_luadocer.util.lua]
    [_luadocer.taglet.standard.lua]----->[lfs.so]
    [_luadocer.taglet.standard.lua]----->[_luadocer.taglet.standard.tags.lua]
    [_luadocer.taglet.standard.lua]----->[comments.init.lua]
        
        'standard
        [_luadocer.taglet.standard.tags.lua]----->[_luadocer.init.lua]
        [_luadocer.taglet.standard.tags.lua]----->[_luadocer.util.lua]
        [_luadocer.taglet.standard.tags.lua]----->[_luadocer.taglet.standard.aliases.lua]

'luaplantuml
[luaplantuml.init.lua]----->[luaplantuml.generate_uml.lua]
[luaplantuml.init.lua]----->[metrics.init.lua]

'luapretty
[luapretty.formatter.lua]----->[lpeg.so]
[luapretty.formatter.lua]----->[leg.parser.lua]
[luapretty.formatter.lua]----->[leg.scanner.lua]
[luapretty.formatter.lua]----->[leg.grammar.lua]
[luapretty.formatter.lua]----->[cosmo.lua]
[luapretty.highlighter.lua]----->[lpeg.so]
[luapretty.highlighter.lua]----->[leg.parser.lua]
[luapretty.highlighter.lua]----->[leg.scanner.lua]
[luapretty.highlighter.lua]----->[leg.grammar.lua]

'metrics
[metrics.init.lua]----->[lpeg.so]
[metrics.init.lua]----->[leg.parser.lua]
[metrics.init.lua]----->[leg.grammar.lua]
[metrics.init.lua]----->[metrics.rules.lua]
[metrics.init.lua]----->[metrics.utils.lua]
[metrics.init.lua]----->[metrics.captures.AST.lua]
[metrics.init.lua]----->[metrics.captures.LOC.lua]
[metrics.init.lua]----->[metrics.captures.infoflow.lua]
[metrics.init.lua]----->[metrics.captures.halstead.lua]
[metrics.init.lua]----->[metrics.captures.functiontree.lua]
[metrics.init.lua]----->[metrics.captures.statements.lua]
[metrics.init.lua]----->[metrics.captures.smells.lua]
[metrics.init.lua]----->[metrics.captures.document_metrics.lua]
[metrics.init.lua]----->[metrics.captures.cyclomatic.lua]
[metrics.init.lua]----->[metrics.captures.block.lua]
[metrics.init.lua]----->[metrics.luadoc.captures.lua]

[metrics.rules.lua]----->[lpeg.so]
[metrics.rules.lua]----->[leg.parser.lua]
[metrics.rules.lua]----->[leg.scanner.lua]

    'captures
    [metrics.captures.AST.lua]----->[metrics.utils.lua]
    [metrics.captures.block.lua]----->[metrics.utils.lua]
    [metrics.captures.cyclomatic.lua]----->[metrics.rules.lua]
    [metrics.captures.document_metrics.lua]----->[metrics.utils.lua]
    [metrics.captures.document_metrics.lua]----->[comments.init.lua]
    [metrics.captures.functiontree.lua]----->[metrics.utils.lua]
    [metrics.captures.halstead.lua]----->[metrics.utils.lua]
    [metrics.captures.halstead.lua]----->[metrics.rules.lua]
    [metrics.captures.infoflow.lua]----->[metrics.utils.lua]
    [metrics.captures.LOC.lua]----->[lpeg.so]
    [metrics.captures.LOC.lua]----->[metrics.rules.lua]
    [metrics.captures.LOC.lua]----->[metrics.utils.lua]
    [metrics.captures.statements.lua]----->[metrics.rules.lua]
    [metrics.captures.statements.lua]----->[metrics.utils.lua]

    'luadoc
    [metrics.luadoc.captures.lua]----->[metrics.luadoc.commentParser.lua]
    [metrics.luadoc.captures.lua]----->[metrics.utils.lua]
    [metrics.luadoc.commentParser.lua]----->[comments.init.lua]

    'templates
    [metrics.templates.docMetricsTemplates.lua]----->[metrics.templates.utils.lua]
    [metrics.templates.funcTableTemplates.lua]----->[metrics.templates.utils.lua]
    [metrics.templates.smellTemplates.lua]----->[metrics.templates.utils.lua]
    [metrics.templates.init.lua]----->[metrics.init.lua]
    [metrics.templates.init.lua]----->[metrics.templates.utils.lua]

@enduml