@startuml
left to right direction
skinparam BackgroundColor transparent
skinparam componentStyle rectangle



package "bin" {
  [luadocer]
  [lua-plantuml]
  [lua-highlighter]
  [lua-formatter]
  [lua-addComments]
  [lfs.so]
}

package "lib" {
    [alt_getopt.lua]
    [cosmo.lua]
    [leg.lua]
    [logging.lua]
    [ltn12.lua]
    [markdown.lua]
    [mime.lua]
    [re.lua]
    [socket.lua]
    [strict.lua]
    [lpeg.so]

    component comments {
        [comments.aliases.lua] 
        [comments.common.lua]
        [comments.custom.lua]
        [comments.explua.lua]
        [comments.init.lua]
        [comments.ldoc.lua]
        [comments.leg.lua]
        [comments.literate.lua]
        [comments.luadoc.lua]
        [comments.templateComments.lua]
    }

    component cosmo {
        [cosmo.fill.lua]
        [cosmo.grammar.lua]
    }

    component leg {
        [leg.grammar.lua]
        [leg.parser.lua]
        [leg.scanner.lua]
    }
    component literate {
        [literate.init.lua]
        [literate.util.lua]
    }
    component logging {
        [logging.console.lua]
        [logging.email.lua]
        [logging.file.lua]
        [logging.rolling_file.lua]
        [logging.socket.lua]
        [logging.sql.lua]
    }
    component _luadocer {
        [_luadocer.config.lua]
        component doclet {
            [_luadocer.doclet.debug.lua]
            [_luadocer.doclet.formatter.lua]
            component html{
                
            }
            [_luadocer.doclet.html.lua]
            [_luadocer.doclet.raw.lua]
            [_luadocer.doclet.templates.lua]
        }
        [_luadocer.init.lua]
        [_luadocer.io.lua]
        [_luadocer.lp.lua]
        component taglet {

        }
        [_luadocer.util.lua]
    }

    component luaplantuml {
        [luaplantuml.generate_uml.lua]
        [luaplantuml.init.lua]
    }
    component luapretty {
        [luapretty.ast_helper.lua]
        [luapretty.formatter.lua]
        [luapretty.highlighter.lua]
        component templates{
            [luapretty.templates.default.lua]
        }
    }    
    component metrics {

        component captures {

        }
        [metrics.init.lua]
        [metrics.lookup.lua]
        component luadoc {

        }
        [metrics.rules.lua]
        component templates {

        }
        [metrics.utils.lua]
    }
    component mime {
        [mime.core.so]
    }
    component socket {
        [socket.core.so]
    }
}

'luadocer
[luadocer]----->[_luadocer.init.lua]
[luadocer]----->[_luadocer.util.lua]

'lua-addComments
[lua-addComments]----->[comments.templateComments.lua]

'lua-formatter
[lua-formatter]----->[luapretty.formatter.lua]
[lua-formatter]----->[alt_getopt.lua]

'lua-highlighter
[lua-highlighter]----->[luapretty.highlighter.lua]
[lua-highlighter]----->[alt_getopt.lua]
[lua-highlighter]----->[_luadocer.doclet.debug.lua]

'lua-plantuml
[lua-plantuml]----->[luaplantuml.init.lua]
[lua-plantuml]----->[alt_getopt.lua]
[lua-plantuml]----->[lfs.so]


'cosmo
[cosmo.lua]----->[cosmo.grammar.lua]
[cosmo.lua]----->[cosmo.fill.lua]

'leg
[leg.lua]----->[leg.grammar.lua]
[leg.lua]----->[leg.scanner.lua]
[leg.lua]----->[leg.parser.lua]

'mime
[mime.lua]----->[ltn12.lua]
[mime.lua]----->[mime.core.so]

're
[re.lua]----->[lpeg.so]

'socket
[socket.lua]----->[socket.core.so]

'comments
[comments.common.lua]----->[comments.aliases.lua]
[comments.custom.lua]----->[re.lua]
[comments.explua.lua]----->[re.lua]
[comments.explua.lua]----->[comments.common.lua]
[comments.init.lua]----->[re.lua]

[comments.init.lua]----->[comments.explua.lua]
[comments.init.lua]----->[comments.luadoc.lua]
[comments.init.lua]----->[comments.literate.lua]
[comments.init.lua]----->[comments.custom.lua]
[comments.init.lua]----->[comments.ldoc.lua]
[comments.init.lua]----->[comments.leg.lua]

[comments.ldoc.lua]----->[re.lua]
[comments.ldoc.lua]----->[comments.common.lua]
[comments.leg.lua]----->[comments.common.lua]
[comments.literate.lua]----->[re.lua]
[comments.luadoc.lua]----->[comments.common.lua]
[comments.luadoc.lua]----->[re.lua]

[comments.templateComments.lua]----->[metrics.init.lua]
[comments.templateComments.lua]----->[metrics.utils.lua]
[comments.templateComments.lua]----->[metrics.utils.lua]
'je tu este nepouzivana zavislot na getdoc.utils
[comments.templateComments.lua]----->[lfs.so]




@enduml